- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Trraform"
    Trainer: "Sivakumar"
    Duration: "120 Hrs"

  tasks:
  - name: print override information
    vars: #task level information
      Course: "Devops"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}"

  - name: print information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}"       