- name: Variable preference
  hosts: localhost
  vars:
    PERSON1: "RAMESH"
    PERSON2: "SURESH"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: PERSON1
    prompt: Name of PERSON1 is
    private: false
  - name: PERSON2
    prompt: Name of PERSON2 is
    private: false
  tasks:
  - name: check preference
    ansible.builtin.debug:
      msg: "Hi, {{PERSON1}} How are you?. {{PERSON2}} iam Good."