- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default ('Ansible')}}"


- name: convert to upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good morning"
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: convert to lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"   

- name: remove duplicates
  hosts: localhost
  vars: 
    numbers: [1, 2, 4, 5, 4, 6, 8, 8]
  tasks:
  - name: remove duplicates 
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"  

- name: min and max values
  hosts: localhost
  vars:
    ages: [25, 26, 31, 67] 
  tasks:
  - name: print min and max values
    ansible.builtin.debug:
      msg: "min age:{{ ages | min}}, max age:{{ ages | max}}"

- name: dictionary to list 
  hosts: localhost
  vars:
    my_dict:
      Course: Devops
      Trainer: Sivakumar
      Duration: 120hrs
  tasks:
  - name: before conversion
    ansible.builtin.debug:
      msg: "Before Convert: {{ my_dict }}"
  - name: After conversion
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}" 

- name: Convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - { 'key': 'Course', 'value': 'Devops' }  
  tasks:
  - name: before conversion
    ansible.builtin.debug:
      msg: "Before Convert: {{ my_list }}"
  - name: After conversion
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}" 
