- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default ('Ansible')}}"


- name: convert to upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good morning"
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: convert to lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"      