- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default ('Ansible')}}"


- name: convert to upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good morning"
  tasks:
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

- name: convert to lower case
  hosts: localhost
  vars:
    greeting: "HELLO, GOOD MORNING"
  tasks:
  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"   

- name: remove duplicates
  hosts: localhost
  vars: 
    numbers: [1, 2, 4, 5, 4, 6, 8, 8]
  tasks:
  - name: remove duplicates 
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"  

- name: min and max values
  hosts: localhost
  vars:
    ages: [25, 26, 31, 67] 
  tasks:
  - name: print min and max values
    ansible.builtin.debug:
      msg: "min age:{{ ages | min}}, max age:{{ ages | max}}"              